import type { Metadata } from "next";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

export const metadata: Metadata = {
	title: "assistant-ui starter app",
	description: "Generated by create-assistant-ui",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className="antialiased">
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	);
}
